/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as IndexRouteImport } from './routes/index'

const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patrocinadores': typeof PatrocinadoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patrocinadores': typeof PatrocinadoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patrocinadores': typeof PatrocinadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patrocinadores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patrocinadores'
  id: '__root__' | '/' | '/patrocinadores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
